@startuml Relativity.Testing.Framework Logging Sequence Diagram

box "Relativity.Testing.Framework" #LightGreen
participant "CoreComponent"
end box

box "Windsor" #LightBlue
participant "LoggingService"
end box

box "Log Files" #LightYellow
participant "Log File"
end box

"CoreComponent" -> "LoggingService" : CoreComponent registers LoggingService
"LoggingService" -> "Log File" : LoggingService writes to Log File

@enduml