@startuml Relativity.Testing.Framework Logging Sequence Diagram
box "TestCode" #LimeGreen
participant "TestCode"
end box


box "Relativity.Testing.Framework" #Orange
participant "RelativityFacade"
participant "WindsorContainer"
participant "LoggingService"
end box

box "Std Out" #LightYellow
participant "Std Out"
end box

"CoreComponent" -> "LoggingService" : CoreComponent registers LoggingService
"LoggingService" -> "Log File" : LoggingService writes to Log File

@enduml