@startuml Relativity.Testing.Framework RegisteredServices Sequence Diagram

box "Code using Relativity.Testing.Framework"
participant "TestCode"
end box

box "Relativity.Testing.Framework" #LightGreen
participant "RelativityFacade"
participant "CoreComponent"
end box

"TestCode" -> "RelativityFacade" : TestCode calls RelativityFacade to resolve an interface
"RelativityFacade" -> "CoreComponent" : RelativityFacade requests container in CoreComponent for the class that implements the interface
"CoreComponent" -> "RelativityFacade" : CoreComponent returns implementation to the RelativityFacade
"TestCode" <- "RelativityFacade" : RelativityFacade returns implementation to TestCode

@enduml
