@startuml Relativity.Testing.Framework RegisteredServices Sequence Diagram

box "Code using Relativity.Testing.Framework"
participant "TestCode"
end box

box "Relativity.Testing.Framework" #LightGreen
participant "RelativityFacade"
end box

"TestCode" -> "RelativityFacade" : TestCode calls RelativityFacade to resolve an interface
"TestCode" <- "RelativityFacade" : RelativityFacade returns implementation to TestCode

@enduml
