apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: relativity-testing-framework-repo
  description: Relativity.Testing.Framework handles configuration management and object models.
  annotations:
    github.com/project-slug: relativitydev/relativity.testing.framework
spec:
  type: repository
  lifecycle: production
  owner: ptci-1599
  system: relativity-testing-framework

---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: relativity-testing-framework
  description: Relativity.Testing.Framework is a set of C#/NuGet libraries that abstracts out common functionality for test setup and teardown and creating artifacts.
spec:
  owner: ptci-1599
