name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
   - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      placeholder: Code example or detailed description of the steps to reproduce the issue.
    validations:
      required: true
   - type: input
    id: framework-version
    attributes:
      label: Relativity Testing Framework versions
      description: Relativity.Testing.Framework version used
      placeholder: Which Relativity.Testing.Framework packages and which versions of them are being used.
    validations:
      required: true
   - type: input
    id: environment-version
    attributes:
      label: Environment details
      description: Type and version of environment
      placeholder: Which type and version of environment is being tested against.
    validations:
      required: true
   - type: textarea
    id: link-testcase
    attributes:
      label: Test Case
      description: Links to a test case where this can be reproduced
      placeholder: Links to a test case where this can be reproduced, if applicable.
    validations:
      required: false
   - type: textarea
    id: link-pipeline
    attributes:
      label: Affected Pipelines
      description: Links to affected pipelines
      placeholder: Links to affected pipelines, if applicable.
    validations:
      required: false
   - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Description of expected behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
   - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens
      placeholder: A clear and concise description of what actually happens.
    validations:
      required: true
   - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Any screenshots to help explain the problem.
      placeholder: If applicable, add screenshots to help explain the problem.
    validations:
      required: false
   - type: markdown
    attributes:
      value: Please provide following details to have us better understand the context:
                Has this problem started happening recently, or has it always been a problem?
                Does the problem occur consistently, or is intermittent?
                Have you asked a team mate if they've encountered this issue before?
                Have you reproduced the issue locally?
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Please answer questions from the above if aplicable
      placeholder: 
    validations:
      required: false
        