@startuml Relativity.Testing.Framework Interceptors Sequence Diagram

box "System Under Test" #LightYellow
participant "RelativityFacade"
end box

box "Relativity.Testing.Framework" #LightGreen
participant "CoreComponent"
end box

box "Windsor" #LightBlue
participant "Container"
end box

"RelativityFacade" -> "CoreComponent" : RelativityFacade relies on CoreComponent
"CoreComponent" -> "Container" : CoreComponent registers ConfigurationService
"CoreComponent" -> "Container" : CoreComponent registers LogService
"CoreComponent" -> "Container" : CoreComponent registers ConfigurationRelativityInstanceVersionResolveService
"CoreComponent" -> "Container" : CoreComponent registers VersionRangeMatchService
"CoreComponent" -> "Container" : CoreComponent registers StrategyResolveService
"CoreComponent" -> "Container" : CoreComponent registers ObjectMappingService
"CoreComponent" -> "Container" : CoreComponent registers JsonObjectMappingService
"CoreComponent" -> "Container" : CoreComponent registers ApplicationInsightsTelemetryClient
"CoreComponent" -> "Container" : CoreComponent registers LoggingInterceptor
"CoreComponent" -> "Container" : CoreComponent registers JsonObjectMappingService
"CoreComponent" -> "Container" : CoreComponent resolves Kernel

@enduml