@startuml Relativity.Testing.Framework Interceptors Sequence Diagram

box "System Under Test" #LightYellow
participant "RelativityFacade"
end box

box "Relativity.Testing.Framework" #LightGreen
participant "CoreComponent"
end box

box "Windsor" #LightBlue
participant "Container"
end box

"RelativityFacade" -> "CoreComponent" : RelativityFacade relies on CoreComponent
"CoreComponent" -> "CoreComponent" : CoreComponent creates ConfigurationService and LogService to be registered
"CoreComponent" -> "Container" : CoreComponent registers services

@enduml